//
//  Subject.swift
//  playkuround-iOS
//
//  Created by Seoyeon Choi on 5/30/24.
//

import Foundation

struct Subject {
    let type: SubjectType
    let title: String
    var xPosition: CGFloat = 60
    var yPosition: CGFloat = 0
}

enum SubjectType {
    case basic // 기본교양
    case advanced // 심화교양
    case department // 학과교양
}

/// 수강신청 ALL 클릭 과목 리스트
let subjectList: [Subject] = [
    // 기초교양-10개
    Subject(type: .basic, title: "대학영어"),
    Subject(type: .basic, title: "대학일본어"),
    Subject(type: .basic, title: "비판적사고와토론"),
    Subject(type: .basic, title: "창조적사고와표현"),
    Subject(type: .basic, title: "인문사회글쓰기"),
    Subject(type: .basic, title: "사회봉사"),
    Subject(type: .basic, title: "컴퓨팅적사고"),
    Subject(type: .basic, title: "실전취업특강"),
    Subject(type: .basic, title: "외국인글쓰기"),
    Subject(type: .basic, title: "벤처창업및경영"),
    
    // 심화교양-29개
    Subject(type: .advanced, title: "논리와사고"),
    Subject(type: .advanced, title: "야외스포츠"),
    Subject(type: .advanced, title: "생활건강"),
    Subject(type: .advanced, title: "과학사"),
    Subject(type: .advanced, title: "요가와명상"),
    Subject(type: .advanced, title: "하모니인건국"),
    Subject(type: .advanced, title: "교육과인간"),
    Subject(type: .advanced, title: "영화영어"),
    Subject(type: .advanced, title: "말과승마"),
    Subject(type: .advanced, title: "철학산책"),
    Subject(type: .advanced, title: "명저읽기"),
    Subject(type: .advanced, title: "신화와영화"),
    Subject(type: .advanced, title: "언어와마음"),
    Subject(type: .advanced, title: "기초글쓰기"),
    Subject(type: .advanced, title: "재무와회계"),
    Subject(type: .advanced, title: "인구의정치학"),
    Subject(type: .advanced, title: "과학의원리"),
    Subject(type: .advanced, title: "지리와이슈"),
    Subject(type: .advanced, title: "삶과소통"),
    Subject(type: .advanced, title: "미디어영어"),
    Subject(type: .advanced, title: "소비와행복"),
    Subject(type: .advanced, title: "윤리와삶"),
    Subject(type: .advanced, title: "상실과회복"),
    Subject(type: .advanced, title: "경제학입문"),
    Subject(type: .advanced, title: "서양문명사"),
    Subject(type: .advanced, title: "동양의지혜"),
    Subject(type: .advanced, title: "선거와여론"),
    Subject(type: .advanced, title: "성과문학"),
    Subject(type: .advanced, title: "정치학입문"),
    
    // 학과교양-61개
    Subject(type: .department, title: "문예창작"),
    Subject(type: .department, title: "영어사"),
    Subject(type: .department, title: "사서강독"),
    Subject(type: .department, title: "논리학"),
    Subject(type: .department, title: "한국고대사"),
    Subject(type: .department, title: "지형학"),
    Subject(type: .department, title: "미디어심리학"),
    Subject(type: .department, title: "상징과이미지"),
    Subject(type: .department, title: "환및가군"),
    Subject(type: .department, title: "현대광학"),
    Subject(type: .department, title: "생화학"),
    Subject(type: .department, title: "건축설비"),
    Subject(type: .department, title: "구조역학"),
    Subject(type: .department, title: "로봇공학"),
    Subject(type: .department, title: "전자회로"),
    Subject(type: .department, title: "표면화학"),
    Subject(type: .department, title: "컴파일러"),
    Subject(type: .department, title: "금융공학"),
    Subject(type: .department, title: "품질경영"),
    Subject(type: .department, title: "면역학"),
    Subject(type: .department, title: "화장품학"),
    Subject(type: .department, title: "정당론"),
    Subject(type: .department, title: "중급거시"),
    Subject(type: .department, title: "정책학개론"),
    Subject(type: .department, title: "국제재무"),
    Subject(type: .department, title: "데이터마이닝"),
    Subject(type: .department, title: "공기업경영론"),
    Subject(type: .department, title: "중국문화론"),
    Subject(type: .department, title: "원가회계"),
    Subject(type: .department, title: "혁신경영"),
    Subject(type: .department, title: "부동산실습"),
    Subject(type: .department, title: "고체물리"),
    Subject(type: .department, title: "전산모델링"),
    Subject(type: .department, title: "인공신경망"),
    Subject(type: .department, title: "화장품화학"),
    Subject(type: .department, title: "조직학"),
    Subject(type: .department, title: "약리학"),
    Subject(type: .department, title: "효소공학"),
    Subject(type: .department, title: "의약화학"),
    Subject(type: .department, title: "유전체학"),
    Subject(type: .department, title: "가축면역학"),
    Subject(type: .department, title: "농업경제학"),
    Subject(type: .department, title: "우유과학"),
    Subject(type: .department, title: "식품학개론"),
    Subject(type: .department, title: "육수학"),
    Subject(type: .department, title: "조경구조학"),
    Subject(type: .department, title: "임상로테이션"),
    Subject(type: .department, title: "광고디자인"),
    Subject(type: .department, title: "디자인기획"),
    Subject(type: .department, title: "테일러링"),
    Subject(type: .department, title: "아트타일"),
    Subject(type: .department, title: "입체일반"),
    Subject(type: .department, title: "즉흥연기"),
    Subject(type: .department, title: "초급일본어"),
    Subject(type: .department, title: "위상수학"),
    Subject(type: .department, title: "육상경기"),
    Subject(type: .department, title: "합창합주"),
    Subject(type: .department, title: "교수설계"),
    Subject(type: .department, title: "영어작문"),
    Subject(type: .department, title: "미디어통역"),
    Subject(type: .department, title: "국제통상정책")
]

// 영어
let subjectListEnglish: [Subject] = [
    // 기초교양-10개
    Subject(type: .basic, title: "College English"),
    Subject(type: .basic, title: "College Japanese"),
    Subject(type: .basic, title: "Critical Thinking and Discussion"),
    Subject(type: .basic, title: "Creative Thinking and Expression"),
    Subject(type: .basic, title: "Humanities and Social Studies Writing"),
    Subject(type: .basic, title: "Community Service"),
    Subject(type: .basic, title: "Computational Thinking"),
    Subject(type: .basic, title: "Practical Employment"),
    Subject(type: .basic, title: "Foreign Language Writing"),
    Subject(type: .basic, title: "Venture Startup and Management"),
    
    // 심화교양-29개
    Subject(type: .advanced, title: "Logic and thinking"),
    Subject(type: .advanced, title: "Outdoor Sports"),
    Subject(type: .advanced, title: "Life and Health"),
    Subject(type: .advanced, title: "History of Science"),
    Subject(type: .advanced, title: "Yoga and Meditation"),
    Subject(type: .advanced, title: "Harmony Human Resources"),
    Subject(type: .advanced, title: "Education and Humans"),
    Subject(type: .advanced, title: "Film English"),
    Subject(type: .advanced, title: "Horses and Riding"),
    Subject(type: .advanced, title: "Philosophy Walk"),
    Subject(type: .advanced, title: "Read a great book"),
    Subject(type: .advanced, title: "Mythology and Movies"),
    Subject(type: .advanced, title: "Language and the Mind"),
    Subject(type: .advanced, title: "Basic Writing"),
    Subject(type: .advanced, title: "Finance and Accounting"),
    Subject(type: .advanced, title: "Politics of Population"),
    Subject(type: .advanced, title: "Principles of Science"),
    Subject(type: .advanced, title: "Geography and Issues"),
    Subject(type: .advanced, title: "Life and Communication"),
    Subject(type: .advanced, title: "Media English"),
    Subject(type: .advanced, title: "Consumption and Happiness"),
    Subject(type: .advanced, title: "Ethics and Life"),
    Subject(type: .advanced, title: "Loss and Recovery"),
    Subject(type: .advanced, title: "Introduction to Economics"),
    Subject(type: .advanced, title: "History of Western Civilization"),
    Subject(type: .advanced, title: "Eastern Wisdom"),
    Subject(type: .advanced, title: "Elections and Public Opinion"),
    Subject(type: .advanced, title: "Performance Literature"),
    Subject(type: .advanced, title: "Introduction to Political Science"),
    
    // 학과교양-61개
    Subject(type: .department, title: "Creative Writing"),
    Subject(type: .department, title: "English History"),
    Subject(type: .department, title: "Librarianship"),
    Subject(type: .department, title: "Logic"),
    Subject(type: .department, title: "Korean Ancient History"),
    Subject(type: .department, title: "Geomorphology"),
    Subject(type: .department, title: "Media Psychology"),
    Subject(type: .department, title: "Symbols and Images"),
    Subject(type: .department, title: "Patronymics"),
    Subject(type: .department, title: "Modern Optics"),
    Subject(type: .department, title: "Biochemistry"),
    Subject(type: .department, title: "Building Construction"),
    Subject(type: .department, title: "Structural Mechanics"),
    Subject(type: .department, title: "Robotics"),
    Subject(type: .department, title: "Electronic Circuits"),
    Subject(type: .department, title: "Surface Chemistry"),
    Subject(type: .department, title: "Compilers"),
    Subject(type: .department, title: "Financial Engineering"),
    Subject(type: .department, title: "Quality Management"),
    Subject(type: .department, title: "Immunology"),
    Subject(type: .department, title: "Cosmetology"),
    Subject(type: .department, title: "Justification"),
    Subject(type: .department, title: "Intermediate Macro"),
    Subject(type: .department, title: "Introduction to Policy Studies"),
    Subject(type: .department, title: "International Finance"),
    Subject(type: .department, title: "Data Mining"),
    Subject(type: .department, title: "Public Management"),
    Subject(type: .department, title: "Chinese Culture"),
    Subject(type: .department, title: "Cost Accounting"),
    Subject(type: .department, title: "Innovation Management"),
    Subject(type: .department, title: "Real Estate Practice"),
    Subject(type: .department, title: "Solid State Physics"),
    Subject(type: .department, title: "Computational Modeling"),
    Subject(type: .department, title: "Artificial Neural Networks"),
    Subject(type: .department, title: "Cosmetic Chemistry"),
    Subject(type: .department, title: "Histology"),
    Subject(type: .department, title: "Pharmacology"),
    Subject(type: .department, title: "Enzyme Engineering"),
    Subject(type: .department, title: "Medicinal Chemistry"),
    Subject(type: .department, title: "Genomics"),
    Subject(type: .department, title: "Animal Immunology"),
    Subject(type: .department, title: "Agricultural Economics"),
    Subject(type: .department, title: "Milk Science"),
    Subject(type: .department, title: "Introduction to Food Science"),
    Subject(type: .department, title: "Meat Science"),
    Subject(type: .department, title: "Landscape Architecture"),
    Subject(type: .department, title: "Clinical Rotations"),
    Subject(type: .department, title: "Advertising Design"),
    Subject(type: .department, title: "Design Planning"),
    Subject(type: .department, title: "Tailoring"),
    Subject(type: .department, title: "ArtTiles"),
    Subject(type: .department, title: "Stereoscopy, general"),
    Subject(type: .department, title: "Improvisation"),
    Subject(type: .department, title: "Beginner Japanese"),
    Subject(type: .department, title: "Topology"),
    Subject(type: .department, title: "Track and Field"),
    Subject(type: .department, title: "Choral Ensemble"),
    Subject(type: .department, title: "Instructional Design"),
    Subject(type: .department, title: "English Composition"),
    Subject(type: .department, title: "Media Interpretation"),
    Subject(type: .department, title: "International Trade Policy")
]

// 중국어
let subjectListChinese: [Subject] = [
    // 기초교양-10개
    Subject(type: .basic, title: "大学英语"),
    Subject(type: .basic, title: "大学日语"),
    Subject(type: .basic, title: "批判性思维与辩论"),
    Subject(type: .basic, title: "创造性思维与表达"),
    Subject(type: .basic, title: "人文社会写作"),
    Subject(type: .basic, title: "社会服务"),
    Subject(type: .basic, title: "计算思维"),
    Subject(type: .basic, title: "实战就业特训"),
    Subject(type: .basic, title: "外国人写作"),
    Subject(type: .basic, title: "风险创业与管理"),
    
    // 심화교양-29개
    Subject(type: .advanced, title: "逻辑与思维"),
    Subject(type: .advanced, title: "户外运动"),
    Subject(type: .advanced, title: "生活健康"),
    Subject(type: .advanced, title: "科学史"),
    Subject(type: .advanced, title: "瑜伽与冥想"),
    Subject(type: .advanced, title: "哈莫尼在建国"),
    Subject(type: .advanced, title: "教育与人"),
    Subject(type: .advanced, title: "电影英语"),
    Subject(type: .advanced, title: "语言与马术"),
    Subject(type: .advanced, title: "哲学散步"),
    Subject(type: .advanced, title: "名著阅读"),
    Subject(type: .advanced, title: "神话与电影"),
    Subject(type: .advanced, title: "语言与心灵"),
    Subject(type: .advanced, title: "基础写作"),
    Subject(type: .advanced, title: "财务与会计"),
    Subject(type: .advanced, title: "人口政治学"),
    Subject(type: .advanced, title: "科学原理"),
    Subject(type: .advanced, title: "地理与议题"),
    Subject(type: .advanced, title: "生活与沟通"),
    Subject(type: .advanced, title: "媒体英语"),
    Subject(type: .advanced, title: "消费与幸福"),
    Subject(type: .advanced, title: "伦理与生活"),
    Subject(type: .advanced, title: "失落与恢复"),
    Subject(type: .advanced, title: "经济学导论"),
    Subject(type: .advanced, title: "西方文明史"),
    Subject(type: .advanced, title: "东方智慧"),
    Subject(type: .advanced, title: "选举与舆论"),
    Subject(type: .advanced, title: "成果与文学"),
    Subject(type: .advanced, title: "政治学导论"),

    // 학과교양-61개
    Subject(type: .department, title: "文艺创作"),
    Subject(type: .department, title: "英语史"),
    Subject(type: .department, title: "图书馆阅读"),
    Subject(type: .department, title: "逻辑学"),
    Subject(type: .department, title: "韩国古代史"),
    Subject(type: .department, title: "地形学"),
    Subject(type: .department, title: "媒体心理学"),
    Subject(type: .department, title: "象征与形象"),
    Subject(type: .department, title: "环与加群"),
    Subject(type: .department, title: "现代光学"),
    Subject(type: .department, title: "生物化学"),
    Subject(type: .department, title: "建筑设备"),
    Subject(type: .department, title: "结构力学"),
    Subject(type: .department, title: "机器人学"),
    Subject(type: .department, title: "电子电路"),
    Subject(type: .department, title: "表面化学"),
    Subject(type: .department, title: "编译器"),
    Subject(type: .department, title: "金融工程"),
    Subject(type: .department, title: "质量管理"),
    Subject(type: .department, title: "免疫学"),
    Subject(type: .department, title: "化妆品学"),
    Subject(type: .department, title: "政党论"),
    Subject(type: .department, title: "中级宏观经济学"),
    Subject(type: .department, title: "政策学导论"),
    Subject(type: .department, title: "国际财务"),
    Subject(type: .department, title: "数据挖掘"),
    Subject(type: .department, title: "国有企业管理论"),
    Subject(type: .department, title: "中国文化论"),
    Subject(type: .department, title: "成本会计"),
    Subject(type: .department, title: "创新管理"),
    Subject(type: .department, title: "房地产实习"),
    Subject(type: .department, title: "固体物理"),
    Subject(type: .department, title: "计算建模"),
    Subject(type: .department, title: "人工神经网络"),
    Subject(type: .department, title: "化妆品化学"),
    Subject(type: .department, title: "组织学"),
    Subject(type: .department, title: "药理学"),
    Subject(type: .department, title: "酶工程"),
    Subject(type: .department, title: "药物化学"),
    Subject(type: .department, title: "基因组学"),
    Subject(type: .department, title: "畜牧免疫学"),
    Subject(type: .department, title: "农业经济学"),
    Subject(type: .department, title: "牛奶科学"),
    Subject(type: .department, title: "食品学导论"),
    Subject(type: .department, title: "肉类科学"),
    Subject(type: .department, title: "景观结构学"),
    Subject(type: .department, title: "临床轮转"),
    Subject(type: .department, title: "广告设计"),
    Subject(type: .department, title: "设计规划"),
    Subject(type: .department, title: "裁剪"),
    Subject(type: .department, title: "艺术瓷砖"),
    Subject(type: .department, title: "立体一般"),
    Subject(type: .department, title: "即兴表演"),
    Subject(type: .department, title: "初级日语"),
    Subject(type: .department, title: "拓扑学"),
    Subject(type: .department, title: "田径"),
    Subject(type: .department, title: "合唱与乐队"),
    Subject(type: .department, title: "教学设计"),
    Subject(type: .department, title: "英语写作"),
    Subject(type: .department, title: "媒体翻译"),
    Subject(type: .department, title: "国际贸易政策"),
]
